# This docker-stack file demos how to use the pycsw docker image with a
# postgis database
#
# Use it with docker-compose or in a docker swarm:
#
# docker-compose --file docker-stack.yml --project pycsw up

version: "3"

services:

  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: pycsw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  pycsw:
    image: ricardogsilva/pycsw:${PYCSW_DOCKER_VERSION}
    ports:
      - "8000:8000"
    volumes:
      - ./docker-stack-pycsw.cfg:/etc/pycsw/pycsw.cfg
    command: [--verbose]


volumes:
  db-data:
